# ============================
# Pinecone
# ============================
pinecone.api.key=pcsk_4wArr8_6a1LrjJDZbsmksMzNZDkFpnBrs2gss918tgexyyvQgQSW1aUVGqStvYCdUSqiLg
pinecone.host=https://chatbot-y4ojuuz.svc.aped-4627-b74a.pinecone.io
pinecone.index.name=medical-chatbot-ollama

# ============================
# Ollama
# ============================
ollama.base-url=http://localhost:11434
ollama.embeddings-path=/api/embeddings
ollama.generate-path=/api/generate


# ============================
# Server
# ============================
server.port=8080
spring.http.client.factory=jdk

