# Hugging Face
huggingface.api.key=${HUGGINGFACE_API_KEY:}

# Pinecone
pinecone.api.key=pcsk_2dpnua_DzrGwtVy5ScmuRB2ZKWyKEXnvJQq835YxCzvGvws7uKJVFT2V7BFqX3fjM8L7io
pinecone.environment=us-east1-gcp
pinecone.index.name=medical-chatbot


# Ollama (or any LLM endpoint)
ollama.url=${OLLAMA_URL:http://localhost:11434}

# chunking config
rag.chunk.size=500
rag.chunk.overlap=20

# server port
server.port=8080
