# ============================
# Pinecone
# ============================
pinecone.api.key=${PINECONE_API_KEY}
pinecone.host=${PINECONE_HOST}
pinecone.index.name=${PINECONE_INDEX}


# ============================
# Ollama
# ============================
ollama.base-url=http://host.docker.internal:11434
ollama.embeddings-path=/api/embeddings
ollama.generate-path=/api/generate


# ============================
# Server
# ============================
server.port=8081
spring.http.client.factory=jdk

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#LLM
llm.api.url=${LLM_API_URL:http://localhost:11434}



